# docker compose app nginx
services:
  nginx:
    build: .
    container_name: nginx-container
    volumes:
      - ./files-nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./files-nginx/proxy_settings.conf:/etc/nginx/proxy_settings.conf
      - ./files-nginx/logrotate:/etc/logrotate.d/nginx
      - ./files-nginx/sites-available:/etc/nginx/sites-available
      - ./files-nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./files-nginx/logs:/var/log/nginx
      - ./files-nginx/certbot/conf:/etc/letsencrypt  # Volume para certificados SSL
      - ./files-nginx/certbot/www:/var/www/certbot  # Volume para desafios do Certbot
      - /tmp:/tmp
    ports:
      - "80:80"
      - "443:443"  # Expor a porta HTTPS
    restart: always
    networks:
      - nginx-network

  nginx-backend:
    build: ./backend-fastapi
    container_name: nginx-backend
    volumes:
      - ./files-nginx:/etc/nginx
      - /var/run/docker.sock:/var/run/docker.sock  # Montando o socket do Docker
      - /tmp:/tmp
    depends_on:
      - nginx
    ports:
      - "${NGINXSERVICE_PORT}:8000"
    restart: always
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
