services:
  nginx-container:
    image: nginx:latest
    volumes:
      - ./nginx-content/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-content/sites-available:/etc/nginx/sites-available
      - ./nginx-content/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx-content/logs:/var/log/nginx
    ports:
      - "80:80"
    networks:
      - nginx-network

  app-nginx:
    build: ./app-nginx
    volumes:
      - ./nginx-content:/etc/nginx
      - /var/run/docker.sock:/var/run/docker.sock  # Montando o socket do Docker
    networks:
      - nginx-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx-content/certbot-etc:/etc/letsencrypt
      - ./nginx-content/certbot-var:/var/lib/letsencrypt
      - ./nginx-content/sites-enabled:/var/www/certbot

networks:
  nginx-network:
    driver: bridge
