version: '3.8'

services:
  nginx-container:
    image: nginx:latest
    container_name: nginx-container
    volumes:
      - ./nginx-content/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-content/sites-available:/etc/nginx/sites-available
      - ./nginx-content/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx-content/logs:/var/log/nginx
      - ./nginx-content/certbot/conf:/etc/letsencrypt  # Volume para certificados SSL
      - ./nginx-content/certbot/www:/var/www/certbot  # Volume para desafios do Certbot
    ports:
      - "80:80"
      - "443:443"  # Expor a porta HTTPS
    networks:
      - nginx-network
    restart: unless-stopped

  app-nginx:
    build: ./app-nginx
    container_name: app-nginx
    volumes:
      - ./nginx-content:/etc/nginx
      - /var/run/docker.sock:/var/run/docker.sock  # Montando o socket do Docker
    networks:
      - nginx-network
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./nginx-content/certbot/conf:/etc/letsencrypt  # Volume para certificados SSL
      - ./nginx-content/certbot/www:/var/www/certbot  # Volume para desafios do Certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"  # Renovação automática
    networks:
      - nginx-network
    restart: unless-stopped

networks:
  nginx-network:
    driver: bridge