[pytest]
# Diz para o pytest considerar 'src' como raiz dos pacotes
pythonpath = nginxsrc/

# Opcional: padrão dos arquivos de teste
python_files = test_*.py
python_classes = Test*
python_functions = test_*
